/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";
import { MeshPhysicalMaterial } from "three";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/ps2_baked_black.glb");
  const material = new MeshPhysicalMaterial({
    color: "#1400bc",
    opacity: 1,
    roughness: 0,
    transmission: 1,
    thickness: 1,
  });
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["CameraAction"].play();
  });
  useEffect(() => {
    actions["Cube.001Action"].play();
  });
  useEffect(() => {
    actions["Cube.002Action"].play();
  });
  useEffect(() => {
    actions["Cube.003Action"].play();
  });
  useEffect(() => {
    actions["Cube.004Action"].play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group position={[0, 8.34, 0]} rotation={[1.89, 0.88, -2.05]}>
          <pointLight
            intensity={1171.8}
            decay={2}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <group
          name="Camera"
          position={[-0.2, 10.28, 1.61]}
          rotation={[0.1, 0, 0]}
        >
          <PerspectiveCamera
            makeDefault={true}
            far={100}
            near={0.1}
            fov={49.43}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <group />
        <mesh geometry={nodes.Grid.geometry} material={materials.pilares} />
        <mesh
          geometry={nodes.Plane.geometry}
          material={materials.Black}
          position={[0, 0.02, 0]}
          scale={[10.18, 1, 6.03]}
        />
        <mesh
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={material}
          position={[-2.22, 5.05, -0.25]}
          rotation={[-0.4, -0.28, 0.58]}
          scale={0.3}
        />
        <mesh
          name="Cube002"
          geometry={nodes.Cube002.geometry}
          material={material}
          position={[2.98, 5.23, -0.61]}
          rotation={[-0.4, -0.28, 0.58]}
          scale={0.3}
        />
        <mesh
          name="Cube003"
          geometry={nodes.Cube003.geometry}
          material={material}
          position={[-2.83, 5.87, 2.11]}
          rotation={[-0.4, -0.28, 0.58]}
          scale={0.3}
        />
        <mesh
          name="Cube004"
          geometry={nodes.Cube004.geometry}
          material={material}
          position={[-0.29, 4.63, 0.92]}
          rotation={[-0.4, -0.28, 0.58]}
          scale={0.3}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ps2_baked_black.glb");
