/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, PerspectiveCamera, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, animations } = useGLTF("/ps2_baked.glb");
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    actions["CameraAction"].play();
  });
  useEffect(() => {
    actions["Cube.001Action"].play();
  });
  useEffect(() => {
    actions["Cube.002Action"].play();
  });
  useEffect(() => {
    actions["Cube.003Action"].play();
  });
  useEffect(() => {
    actions["Cube.004Action"].play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group position={[0, 1900, 0]} rotation={[1.89, 0.88, -2.05]}>
          <pointLight
            intensity={50}
            decay={1}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <group
          name="Camera"
          position={[-0.2, 10.28, 1.61]}
          rotation={[0.1, 0, 0]}
        >
          <PerspectiveCamera
            name="Camera_Orientation"
            makeDefault={true}
            far={100}
            near={0.1}
            fov={49.43}
            rotation={[-Math.PI / 2, 0, 0]}
          />
        </group>
        <group />
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
          position={[2.54, 1.06, -9.78]}
          scale={[0.96, 2.99, 0.96]}
        />
        <mesh geometry={nodes.Grid.geometry} material={nodes.Grid.material} />
        <mesh
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={nodes.Cube001.material}
          position={[-2.22, 5.05, -0.25]}
          rotation={[-0.4, -0.28, 0.58]}
          scale={0.3}
        />
        <mesh
          name="Cube002"
          geometry={nodes.Cube002.geometry}
          material={nodes.Cube002.material}
          position={[2.98, 5.23, -0.61]}
          rotation={[-0.4, -0.28, 0.58]}
          scale={0.3}
        />
        <mesh
          name="Cube003"
          geometry={nodes.Cube003.geometry}
          material={nodes.Cube003.material}
          position={[-2.83, 5.87, 2.11]}
          rotation={[-0.4, -0.28, 0.58]}
          scale={0.3}
        />
        <mesh
          name="Cube004"
          geometry={nodes.Cube004.geometry}
          material={nodes.Cube004.material}
          position={[-0.29, 4.63, 0.92]}
          rotation={[-0.4, -0.28, 0.58]}
          scale={0.3}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/ps2_baked.glb");
